### ISSUE TITLE
How to use starkbank-ecdsa in react native(expo) project?

### ISSUE THREAD

**Issue by ParkSeungwon** [starkbank/ecdsa-node#18]
I wanted to use this libaray in react native.
In node environment it was OK.
But when I tried to use it in react native, it gave me this error.
Cannot resolve crypto module..

**Comment by leandro-stark** [comment]
Hi, @ParkSeungwon!

It's important to understand that when you use JavaScript in a back-end application with Node.js engine, you can use ECDSA without problem.

In a mobile application, the ReactNative uses JavaScript with V8 engine and this one doesn't have access to the files of the system and the necessary libs from Node.js, so the ECDSA can not work as expected.

That's why you are receiving this error in your log.

We develop a new version of the ECDSA Node to use ReactNative without problem, you can check in this repository:

ecdsa-node-react-native: https://github.com/paulo-stark/ecdsa-node-react-native/tree/feature/remove-node-dependencies

If you have any additional questions, don't hesitate to ask!

Best,
